// src/features/dashboard/components/sections/DietPlanSection.tsx (REFACTORED)

import { type MacroTargets, useNutritionLogs } from "@/features/nutrition";
import type { DashboardCalculations } from "@/shared/types/dashboard";
import { AlertCircle, Plus } from "lucide-react";
import { memo, useMemo, useState } from "react";
import { useDietPlan } from "../../hooks/useDietPlan";
import {
    HydrationPanel,
    MealList,
    MealLogModal,
    MealTabs,
    ProgressCards,
    ShoppingPanel,
    TipsPanel,
} from "../old-dashboard/DietPlan";
import { DietPlanSkeleton } from "../old-dashboard/DietPlan/DietPlanSkeleton";

interface DietPlanSectionProps {
  userId: string;
  calculations: DashboardCalculations;
}

const TABS = [
  {
    name: "Meals",
    bg: "bg-progress-green-emerald",
    color: "text-white",
    ringColor: "focus:ring-emerald-500/50",
  },
  {
    name: "Hydration",
    bg: "bg-progress-blue-cyan",
    color: "text-blue-600 dark:text-blue-400",
    ringColor: "focus:ring-blue-500/50",
  },
  {
    name: "Shopping",
    bg: "bg-progress-green-emerald",
    color: "text-green-600 dark:text-green-400",
    ringColor: "focus:ring-green-500/50",
  },
  {
    name: "Tips",
    bg: "bg-progress-purple-pink",
    color: "text-purple-600 dark:text-purple-400",
    ringColor: "focus:ring-purple-500/50",
  },
];

export const DietPlanSection: React.FC<DietPlanSectionProps> = memo(({ userId, calculations }) => {
  const [showLogModal, setShowLogModal] = useState(false);
  const [expandedMeal, setExpandedMeal] = useState<number | null>(null);
  const [selectedTab, setSelectedTab] = useState(TABS[0].name);

  // Unified data fetching with polling
  const { data: dietPlan, isLoading, isGenerating, isError, errorMessage, hasNoPlan } = useDietPlan(userId);

  // Macro targets for nutrition tracking
  const macroTargets: MacroTargets = useMemo(
    () => ({
      dailyCalories: calculations.goalCalories,
      protein_g: calculations.macros.protein_g,
      carbs_g: calculations.macros.carbs_g,
      fat_g: calculations.macros.fat_g,
    }),
    [calculations]
  );

  const {
    stats: nutritionStats,
    isLoggingMeal,
    refetch,
  } = useNutritionLogs(userId, macroTargets);

  // Use stats from the hook if available, otherwise calculate defaults
  const stats = useMemo(
    () =>
      nutritionStats || {
        totalLoggedToday: 0,
        totalProteinLogged: 0,
        totalCarbsLogged: 0,
        totalFatsLogged: 0,
        remainingCalories: calculations.goalCalories,
        remainingProtein: calculations.macros.protein_g,
        remainingCarbs: calculations.macros.carbs_g,
        remainingFats: calculations.macros.fat_g,
        caloriePercentage: 0,
        proteinPercentage: 0,
        carbsPercentage: 0,
        fatsPercentage: 0,
      },
    [nutritionStats, calculations]
  );

  // Memoized tab panels
  const tabPanels = useMemo(
    () => [
      <MealList
        key="meals"
        dietPlanData={dietPlan?.plan_data!}
        expandedMeal={expandedMeal}
        setExpandedMeal={setExpandedMeal}
      />,
      <HydrationPanel key="hydration" hydrationPlan={dietPlan?.plan_data?.hydration_plan!} />,
      <ShoppingPanel
        key="shopping"
        shoppingList={dietPlan?.plan_data?.shopping_list!}
        mealPrepStrategy={dietPlan?.plan_data?.meal_prep_strategy!}
      />,
      <TipsPanel
        key="tips"
        tips={dietPlan?.plan_data?.personalized_tips!}
        dailyTotals={dietPlan?.plan_data?.daily_totals!}
        variance={dietPlan?.plan_data?.daily_totals?.variance!}
      />,
    ],
    [dietPlan, expandedMeal]
  );

  // Loading state (initial load or generating)
  if (isLoading || isGenerating) {
    return (
      <div className="mx-auto space-y-6">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h2 className="text-3xl font-bold text-gradient-green-emerald mb-2">
              Your Personalized Meal Plan
            </h2>
            <p className="text-muted-foreground">
              {isGenerating ? "Being generated by AI..." : "Loading..."}
            </p>
          </div>
        </div>
        <DietPlanSkeleton />
      </div>
    );
  }

  // Error state
  if (isError) {
    return (
      <div className="mx-auto space-y-6">
        <div className="max-w-4xl mx-auto">
          <div className="bg-red-50 dark:bg-red-900/20 rounded-lg p-8 border border-red-200 dark:border-red-800">
            <div className="flex items-start gap-4">
              <AlertCircle className="h-8 w-8 text-red-600 flex-shrink-0 mt-1" />
              <div>
                <h3 className="text-xl font-bold text-red-900 dark:text-red-100 mb-2">
                  Plan Generation Failed
                </h3>
                <p className="text-red-700 dark:text-red-300 mb-4">
                  {errorMessage || "An error occurred while generating your meal plan."}
                </p>
                <button
                  onClick={() => window.location.reload()}
                  className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
                >
                  Retry
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Empty state - no plan exists
  if (hasNoPlan) {
    return (
      <div className="min-h-screen bg-page-slate-blue p-6">
        <div className="max-w-4xl mx-auto text-center py-12">
          <div className="bg-white/50 dark:bg-slate-900/50 backdrop-blur-sm rounded-md p-12 border border-slate-200/50 dark:border-slate-700/50">
            <Plus className="h-16 w-16 text-primary mx-auto mb-4" />
            <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-2">
              No Diet Plan Yet
            </h3>
            <p className="text-muted-foreground">
              Complete the nutrition quiz to get your personalized AI meal plan!
            </p>
          </div>
        </div>
      </div>
    );
  }

  // Success state - render the meal plan
  return (
    <div className="mx-auto space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h2 className="text-3xl font-bold text-gradient-green-emerald mb-2">
            Your Personalized Meal Plan
          </h2>
          <p className="text-muted-foreground">
            AI-optimized nutrition designed for your goals
          </p>
        </div>
        <button
          onClick={() => setShowLogModal(true)}
          className="px-6 py-3 bg-progress-green-emerald text-white rounded-md font-semibold shadow-lg hover:shadow-xl transform hover:scale-105 transition-all flex items-center gap-2"
        >
          <Plus className="h-5 w-5" /> Log Meal
        </button>
      </div>
      <ProgressCards
        calorieStats={{
          logged: stats.totalLoggedToday,
          target: calculations.goalCalories,
          percentage: stats.caloriePercentage,
          remaining: stats.remainingCalories,
        }}
        proteinStats={{
          logged: stats.totalProteinLogged,
          target: calculations.macros.protein_g,
          percentage: stats.proteinPercentage,
          remaining: stats.remainingProtein,
        }}
        carbsStats={{
          logged: stats.totalCarbsLogged,
          target: calculations.macros.carbs_g,
          percentage: stats.carbsPercentage,
          remaining: stats.remainingCarbs,
        }}
        fatsStats={{
          logged: stats.totalFatsLogged,
          target: calculations.macros.fat_g,
          percentage: stats.fatsPercentage,
          remaining: stats.remainingFats,
        }}
      />
      <MealTabs
        currentTab={selectedTab}
        onTabChange={setSelectedTab}
        tabs={TABS}
        tabPanels={tabPanels}
      />
      <MealLogModal
        userId={userId}
        show={showLogModal}
        setShowLogModal={setShowLogModal}
        onClose={() => setShowLogModal(false)}
        loadTodayLogs={refetch}
        isLogging={isLoggingMeal}
      />
    </div>
  );
});

DietPlanSection.displayName = "DietPlanSection";