/**
 * GreenLean Landing Page V2 - Complete SaaS Redesign
 * Modern hero, features showcase, pricing tiers, and social proof
 */

import { useAuth } from '@/features/auth/hooks/useAuth';
import { cn } from '@/lib/utils';
import { Badge } from '@/shared/components/ui/badge';
import { Button } from '@/shared/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/shared/components/ui/card';
import { motion } from 'framer-motion';
import {
  Apple,
  ArrowRight,
  BarChart3,
  Brain,
  Camera,
  Check,
  ChevronRight,
  Crown,
  Dumbbell,
  Shield,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Zap,
} from 'lucide-react';
import type React from 'react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

const stats = [
  { label: 'Active Users', value: '50K+', icon: Users },
  { label: 'Meals Planned', value: '2M+', icon: Apple },
  { label: 'Success Rate', value: '94%', icon: TrendingUp },
  { label: 'Avg. Weight Loss', value: '12kg', icon: Target },
];

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Meal Plans',
    description: 'Get personalized meal plans generated by advanced AI based on your goals, preferences, and dietary restrictions.',
    tier: 'free',
  },
  {
    icon: Dumbbell,
    title: 'Custom Workout Plans',
    description: 'Access tailored workout routines that adapt to your fitness level and available equipment.',
    tier: 'free',
  },
  {
    icon: BarChart3,
    title: 'Progress Tracking',
    description: 'Monitor weight, measurements, and body composition with detailed charts and insights.',
    tier: 'free',
  },
  {
    icon: Camera,
    title: 'Barcode Scanner',
    description: 'Scan any food product to instantly log nutrition info from our 1M+ food database.',
    tier: 'pro',
  },
  {
    icon: Trophy,
    title: 'Challenges & Rewards',
    description: 'Compete in community challenges and earn badges, XP, and unlock premium themes.',
    tier: 'pro',
  },
  {
    icon: Sparkles,
    title: 'Premium AI Coach',
    description: 'Get advanced personalization, macro cycling, and restaurant meal suggestions with GPT-4.',
    tier: 'premium',
  },
];

const pricingTiers = [
  {
    name: 'Free',
    price: '$0',
    period: 'forever',
    description: 'Perfect for getting started',
    features: [
      'AI meal plan generation (5/month)',
      'Basic workout plans',
      'Manual food logging',
      'Weight tracking',
      'Community access',
      'Standard support',
    ],
    cta: 'Get Started Free',
    popular: false,
    color: 'gray',
  },
  {
    name: 'Pro',
    price: '$12',
    period: 'per month',
    description: 'For serious fitness enthusiasts',
    features: [
      'Unlimited AI meal plans',
      'Advanced workout builder',
      'Barcode scanner',
      'Progress photos & analytics',
      'Challenges & badges',
      'Nutritionix API access',
      'Priority support',
    ],
    cta: 'Start Pro Trial',
    popular: true,
    color: 'primary',
  },
  {
    name: 'Premium',
    price: '$24',
    period: 'per month',
    description: 'Maximum results & personalization',
    features: [
      'Everything in Pro',
      'GPT-4 AI coaching',
      'Macro cycling & meal timing',
      'Restaurant meal suggestions',
      'Video workout demonstrations',
      'Custom themes & UI',
      'White-glove support',
    ],
    cta: 'Start Premium Trial',
    popular: false,
    color: 'accent',
  },
];

const faqs = [
  {
    question: 'How does the AI meal planner work?',
    answer: 'Our AI analyzes your goals, dietary preferences, allergies, and activity level to generate personalized meal plans. Free users get 5 AI-generated plans per month, while Pro and Premium users get unlimited access.',
  },
  {
    question: 'Can I cancel my subscription anytime?',
    answer: 'Yes! You can cancel your subscription at any time with no questions asked. Your access will continue until the end of your billing period.',
  },
  {
    question: 'What makes Premium different from Pro?',
    answer: 'Premium uses GPT-4 for advanced meal personalization, including macro cycling, meal timing optimization, and restaurant menu suggestions. You also get video workout demonstrations and custom themes.',
  },
  {
    question: 'Do you support special diets?',
    answer: 'Absolutely! We support vegan, vegetarian, keto, paleo, gluten-free, dairy-free, and many other dietary preferences. Our AI adapts to your specific needs.',
  },
];

const HomeV2: React.FC = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [billingPeriod, setBillingPeriod] = useState<'monthly' | 'annual'>('monthly');

  const handleGetStarted = () => {
    if (user) {
      navigate('/quiz');
    } else {
      navigate('/register');
    }
  };

  return (
    <div className="overflow-hidden">
      {/* Hero Section */}
      <section className="relative min-h-[90vh] flex items-center justify-center overflow-hidden">
        {/* Animated Background Elements */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div
            className="absolute top-0 right-3/4 w-96 h-96 bg-primary-600/30 rounded-full blur-3xl animate-pulse"
            style={{ animationDuration: '6s' }}
          />
          <div
            className="absolute bottom-0 left-3/4 w-96 h-96 bg-accent-600/20 rounded-full blur-3xl animate-pulse"
            style={{ animationDuration: '6s', animationDelay: '2s' }}
          />
          <div
            className="absolute inset-0 bg-[linear-gradient(var(--grid-color-light)_1px,transparent_1px),linear-gradient(90deg,var(--grid-color-light)_1px,transparent_1px)] bg-[size:72px_72px] dark:bg-[linear-gradient(var(--grid-color-dark)_1px,transparent_1px),linear-gradient(90deg,var(--grid-color-dark)_1px,transparent_1px)]"
          />
        </div>

        <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="max-w-4xl mx-auto text-center">
            {/* Badge */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="mb-6"
            >
              <Badge className="badge-primary px-4 py-2 text-sm">
                <Sparkles className="w-4 h-4 mr-2 inline" />
                Trusted by 50,000+ users worldwide
              </Badge>
            </motion.div>

            {/* Headline */}
            <motion.h1
              className="text-5xl sm:text-6xl md:text-7xl font-bold mb-6 text-gradient"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
            >
              Your AI-Powered
              <br />
              <span className="text-primary">Health Transformation</span>
            </motion.h1>

            {/* Subheadline */}
            <motion.p
              className="text-xl sm:text-2xl mb-10 text-muted-foreground max-w-3xl mx-auto"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
            >
              Get personalized meal plans, workout routines, and nutrition tracking powered by advanced AI.
              Join thousands achieving their health goals faster.
            </motion.p>

            {/* CTAs */}
            <motion.div
              className="flex flex-col sm:flex-row justify-center gap-4 mb-12"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }}
            >
              <Button
                size="lg"
                onClick={handleGetStarted}
                className="text-lg px-8 py-6 shadow-xl hover:shadow-2xl transition-all"
              >
                Start Free Today
                <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
              <Button
                size="lg"
                variant="outline"
                onClick={() => document.getElementById('pricing')?.scrollIntoView({ behavior: 'smooth' })}
                className="text-lg px-8 py-6"
              >
                View Pricing
                <ChevronRight className="ml-2 w-5 h-5" />
              </Button>
            </motion.div>

            {/* Stats */}
            <motion.div
              className="grid grid-cols-2 md:grid-cols-4 gap-6 max-w-4xl mx-auto"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.4 }}
            >
              {stats.map((stat, index) => (
                <Card
                  key={index}
                  className="glass-card"
                >
                  <CardContent className="p-6 text-center">
                    <stat.icon className="w-8 h-8 mx-auto mb-2 text-primary" />
                    <div className="text-3xl font-bold text-foreground mb-1">
                      {stat.value}
                    </div>
                    <div className="text-sm text-muted-foreground">{stat.label}</div>
                  </CardContent>
                </Card>
              ))}
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 bg-background">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          {/* Section Header */}
          <div className="text-center mb-16">
            <Badge className="mb-4">
              <Zap className="w-4 h-4 mr-2 inline" />
              Powerful Features
            </Badge>
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              Everything You Need to
              <span className="text-primary"> Succeed</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              From AI meal planning to progress tracking, we've got you covered at every step
            </p>
          </div>

          {/* Features Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
              >
                <Card className="h-full hover:shadow-xl transition-shadow">
                  <CardHeader>
                    <div className="flex items-start justify-between mb-4">
                      <div className="w-12 h-12 rounded-xl bg-primary flex items-center justify-center">
                        <feature.icon className="w-6 h-6 text-primary-foreground" />
                      </div>
                      {feature.tier !== 'free' && (
                        <Badge variant={feature.tier === 'premium' ? 'default' : 'outline'}>
                          {feature.tier === 'pro' ? (
                            <>
                              <Zap className="w-3 h-3 mr-1" />
                              Pro
                            </>
                          ) : (
                            <>
                              <Crown className="w-3 h-3 mr-1" />
                              Premium
                            </>
                          )}
                        </Badge>
                      )}
                    </div>
                    <CardTitle className="text-xl">{feature.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-muted-foreground">{feature.description}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-24 bg-muted">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          {/* Section Header */}
          <div className="text-center mb-12">
            <Badge className="mb-4">
              <Shield className="w-4 h-4 mr-2 inline" />
              Simple Pricing
            </Badge>
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              Choose Your
              <span className="text-primary"> Perfect Plan</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8">
              Start free, upgrade when you're ready. Cancel anytime, no questions asked.
            </p>

            {/* Billing Toggle */}
            <div className="inline-flex items-center gap-4 bg-background p-2 rounded-full shadow-sm">
              <button
                onClick={() => setBillingPeriod('monthly')}
                className={cn(
                  'px-6 py-2 rounded-full font-medium transition-all',
                  billingPeriod === 'monthly'
                    ? 'bg-primary text-primary-foreground'
                    : 'text-muted-foreground'
                )}
              >
                Monthly
              </button>
              <button
                onClick={() => setBillingPeriod('annual')}
                className={cn(
                  'px-6 py-2 rounded-full font-medium transition-all',
                  billingPeriod === 'annual'
                    ? 'bg-primary text-primary-foreground'
                    : 'text-muted-foreground'
                )}
              >
                Annual
                <Badge className="ml-2 bg-accent text-accent-foreground">Save 20%</Badge>
              </button>
            </div>
          </div>

          {/* Pricing Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {pricingTiers.map((tier, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
                className={cn(
                  'relative',
                  tier.popular && 'md:-mt-4 md:mb-4'
                )}
              >
                <Card className={cn(
                  'h-full relative overflow-hidden',
                  tier.popular && 'border-primary border-2 shadow-2xl'
                )}>
                  {tier.popular && (
                    <div className="absolute top-0 right-0 bg-primary text-primary-foreground px-4 py-1 text-sm font-semibold">
                      Most Popular
                    </div>
                  )}
                  <CardHeader className="text-center pb-8 pt-8">
                    <h3 className="text-2xl font-bold mb-2">{tier.name}</h3>
                    <p className="text-muted-foreground mb-6">{tier.description}</p>
                    <div className="mb-6">
                      <span className="text-5xl font-bold">
                        {billingPeriod === 'annual' && tier.name !== 'Free'
                          ? `$${Math.floor(Number.parseInt(tier.price.slice(1)) * 0.8)}`
                          : tier.price}
                      </span>
                      <span className="text-muted-foreground ml-2">/{tier.period}</span>
                    </div>
                    <Button
                      className="w-full"
                      variant={tier.popular ? 'default' : 'outline'}
                      size="lg"
                      onClick={handleGetStarted}
                    >
                      {tier.cta}
                    </Button>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-3">
                      {tier.features.map((feature, i) => (
                        <li key={i} className="flex items-start">
                          <Check className="w-5 h-5 text-primary mr-3 flex-shrink-0 mt-0.5" />
                          <span className="text-muted-foreground">{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Social Proof / Testimonials */}
      <section className="py-24 bg-background">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge className="mb-4">
              <Star className="w-4 h-4 mr-2 inline fill-current" />
              Success Stories
            </Badge>
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              Loved by
              <span className="text-primary"> Thousands</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Real people, real results. See what our community has to say.
            </p>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-24 bg-muted">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              Frequently Asked
              <span className="text-primary"> Questions</span>
            </h2>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
              >
                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">{faq.question}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-muted-foreground">{faq.answer}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-24 bg-cta">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto text-center text-primary-foreground">
            <motion.h2
              className="text-4xl md:text-5xl font-bold mb-6"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            >
              Ready to Transform Your Health?
            </motion.h2>
            <motion.p
              className="text-xl mb-10 opacity-90"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              viewport={{ once: true }}
            >
              Join 50,000+ users who are achieving their fitness goals with GreenLean.
              Start your free journey today.
            </motion.p>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              viewport={{ once: true }}
            >
              <Button
                size="lg"
                variant="accent"
                onClick={handleGetStarted}
                className="text-lg px-8 py-6 shadow-xl"
              >
                Get Started Free
                <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
            </motion.div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default HomeV2;
