export type LogMethod =
  | "search"
  | "manual"
  | "voice"
  | "barcode"
  | "photo"
  | "ai-plan"
  | "template";

export interface MealItem {
  id?: string; // Generated by UUID
  food_id?: string; // USDA FDC ID or barcode
  food_name: string;
  brand_name?: string;
  serving_qty: number;
  serving_unit: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  fiber?: number;
  sugar?: number;
  sodium?: number;
  source?: LogMethod;
  from_ai_plan?: boolean;
  ai_meal_plan_id?: string;
  plan_meal_name?: string;
  notes?: string;
  // For calc: base per 1 unit/100g
  base_calories?: number;
  base_protein?: number;
  base_carbs?: number;
  base_fats?: number;
  base_fiber?: number;
  base_sugar?: number;
  base_sodium?: number;
  base_serving_unit?: string; // e.g., '100g'
  base_serving_qty?: number;
  // For photo analysis
  confidence?: number;
  portion_estimate?: string;
}

export interface DailyNutritionLog {
  id: string;
  user_id: string;
  log_date: string;
  meal_type: "breakfast" | "lunch" | "dinner" | "snack";
  total_calories: number;
  total_protein: number;
  total_carbs: number;
  total_fats: number;
  notes?: string;
  created_at: string;
  meal_items?: MealItem[]; // Joined in queries
}

export interface MealTemplate {
  id: string;
  user_id: string;
  name: string;
  description?: string;
  meal_type?: string;
  total_calories: number;
  total_protein: number;
  total_carbs: number;
  total_fats: number;
  is_favorite: boolean;
  use_count: number;
  last_used_at?: string;
  created_at: string;
  updated_at: string;
  items?: MealItem[]; // Joined from template_items
}
